/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import classBDD.AlumnosBDD;
import classBDD.EscuelasBDD;
import classDS.AlumnosDS;
import classDS.EscuelasDS;
import javax.swing.table.DefaultTableModel;
public class InterfasAplicacion extends javax.swing.JFrame {

    /**
     * Creates new form InterfasAplicacion
     */
    public InterfasAplicacion() {
        initComponents();
        cargarEscuelas(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Escuelas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_Telefono = new javax.swing.JTextField();
        txt_Direccion = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_mensaje = new javax.swing.JTextField();
        RegistrarEscuelas = new javax.swing.JButton();
        ActualizarEscuelas = new javax.swing.JButton();
        BuscarEscuela = new javax.swing.JButton();
        EliminarEscuela = new javax.swing.JButton();
        LimpiarT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_IDe = new javax.swing.JLabel();
        lbl_cedulaE = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_fechaNac = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_celular = new javax.swing.JLabel();
        lbl_observacion = new javax.swing.JLabel();
        RegistrarEstudiante = new javax.swing.JButton();
        ActualizarEstudiante = new javax.swing.JButton();
        BuscarEstudiante = new javax.swing.JButton();
        EliminarEstudiante = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        txt_IDE = new javax.swing.JTextField();
        txt_cedulaE = new javax.swing.JTextField();
        txt_nombreE = new javax.swing.JTextField();
        txt_fechaNac = new javax.swing.JTextField();
        txt_direccionE = new javax.swing.JTextField();
        txt_emailE = new javax.swing.JTextField();
        txt_celularE = new javax.swing.JTextField();
        txt_observacionE = new javax.swing.JTextField();
        txt_mensajeE = new javax.swing.JTextField();
        list_escuelas = new javax.swing.JComboBox();
        lbl_Escuela = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_general = new javax.swing.JTable();
        buscarGeneral = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_escuelas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escuelas.setName("Escuelas"); // NOI18N

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Telefono:");

        jLabel4.setText("Direccion:");

        jLabel5.setText("Email:");

        txt_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDActionPerformed(evt);
            }
        });

        txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreActionPerformed(evt);
            }
        });

        txt_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TelefonoActionPerformed(evt);
            }
        });

        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });

        RegistrarEscuelas.setText("Registrar");
        RegistrarEscuelas.setName("RegistrarEscuelas"); // NOI18N
        RegistrarEscuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEscuelasActionPerformed(evt);
            }
        });

        ActualizarEscuelas.setText("Actualizar");
        ActualizarEscuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarEscuelasActionPerformed(evt);
            }
        });

        BuscarEscuela.setText("Buscar");
        BuscarEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarEscuelaActionPerformed(evt);
            }
        });

        EliminarEscuela.setText("Eliminar");
        EliminarEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEscuelaActionPerformed(evt);
            }
        });

        LimpiarT.setText("Limpiar Todo");
        LimpiarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Email)
                            .addComponent(txt_Direccion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(44, 44, 44)
                                .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Nombre)))
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RegistrarEscuelas)
                .addGap(37, 37, 37)
                .addComponent(ActualizarEscuelas)
                .addGap(33, 33, 33)
                .addComponent(BuscarEscuela)
                .addGap(37, 37, 37)
                .addComponent(EliminarEscuela)
                .addGap(31, 31, 31)
                .addComponent(LimpiarT)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(txt_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarEscuela)
                    .addComponent(BuscarEscuela)
                    .addComponent(ActualizarEscuelas)
                    .addComponent(RegistrarEscuelas)
                    .addComponent(LimpiarT))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("lbl_ID");
        jLabel2.getAccessibleContext().setAccessibleName("lbl_Nombre");
        jLabel3.getAccessibleContext().setAccessibleName("lbl_telefono");
        jLabel4.getAccessibleContext().setAccessibleName("lbl_Direccion");
        jLabel5.getAccessibleContext().setAccessibleName("lbl_email");
        txt_ID.getAccessibleContext().setAccessibleName("text_ID");
        txt_Nombre.getAccessibleContext().setAccessibleName("txt_Nombre");
        txt_Telefono.getAccessibleContext().setAccessibleName("txt_Telefono");
        txt_Direccion.getAccessibleContext().setAccessibleName("txt_Direccion");
        txt_Email.getAccessibleContext().setAccessibleName("txt_Email");
        txt_mensaje.getAccessibleContext().setAccessibleName("txt_Mensaje");
        RegistrarEscuelas.getAccessibleContext().setAccessibleName("btn_Registrar");
        ActualizarEscuelas.getAccessibleContext().setAccessibleName("btn_Actualizar");
        BuscarEscuela.getAccessibleContext().setAccessibleName("btn_Buscar");
        EliminarEscuela.getAccessibleContext().setAccessibleName("btn_Eliminar");
        LimpiarT.getAccessibleContext().setAccessibleName("btn_Limpiar");

        Escuelas.addTab("Esculela", jPanel1);

        lbl_IDe.setText("ID:");

        lbl_cedulaE.setText("Cedula:");

        lbl_nombre.setText("Nombre:");

        lbl_fechaNac.setText("Fecha de Nacimiento");

        lbl_direccion.setText("Direccion:");

        lbl_email.setText("Email:");

        lbl_celular.setText("# Celular:");

        lbl_observacion.setText("Observaciones");

        RegistrarEstudiante.setText("Registrar");
        RegistrarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEstudianteActionPerformed(evt);
            }
        });

        ActualizarEstudiante.setText("Actualizar");
        ActualizarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarEstudianteActionPerformed(evt);
            }
        });

        BuscarEstudiante.setText("Buscar");
        BuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarEstudianteActionPerformed(evt);
            }
        });

        EliminarEstudiante.setText("Eliminar");
        EliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEstudianteActionPerformed(evt);
            }
        });

        Limpiar.setText("Limpiar Todo");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        txt_cedulaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaEActionPerformed(evt);
            }
        });

        txt_nombreE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreEActionPerformed(evt);
            }
        });

        list_escuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_escuelasActionPerformed(evt);
            }
        });

        lbl_Escuela.setText("Escuelas:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_IDE, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_email, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(RegistrarEstudiante)
                                        .addGap(18, 18, 18)
                                        .addComponent(ActualizarEstudiante)
                                        .addGap(18, 18, 18)
                                        .addComponent(BuscarEstudiante))))
                            .addComponent(lbl_IDe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EliminarEstudiante)
                        .addGap(36, 36, 36)
                        .addComponent(Limpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_fechaNac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_direccion)
                                    .addComponent(lbl_celular)
                                    .addComponent(lbl_observacion))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_direccionE, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_observacionE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                        .addComponent(txt_celularE, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_emailE, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(txt_mensajeE, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_cedulaE)
                                    .addComponent(lbl_nombre))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_cedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbl_Escuela)))
                        .addGap(18, 18, 18)
                        .addComponent(list_escuelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_IDe)
                    .addComponent(txt_IDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Escuela)
                    .addComponent(list_escuelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cedulaE)
                    .addComponent(txt_cedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(txt_nombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fechaNac)
                    .addComponent(txt_fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direccion)
                    .addComponent(txt_direccionE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(txt_emailE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_celular)
                    .addComponent(txt_celularE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_observacion)
                    .addComponent(txt_observacionE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(txt_mensajeE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarEstudiante)
                    .addComponent(ActualizarEstudiante)
                    .addComponent(BuscarEstudiante)
                    .addComponent(EliminarEstudiante)
                    .addComponent(Limpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_IDe.getAccessibleContext().setAccessibleName("lbl_IDe");
        lbl_cedulaE.getAccessibleContext().setAccessibleName("lbl_cedulaE");
        lbl_nombre.getAccessibleContext().setAccessibleName("lbl_nombre");
        lbl_fechaNac.getAccessibleContext().setAccessibleName("lbl_fechaNac");
        lbl_direccion.getAccessibleContext().setAccessibleName("lbl_direccion");
        lbl_email.getAccessibleContext().setAccessibleName("lbl_email");
        lbl_celular.getAccessibleContext().setAccessibleName("lbl_celular");
        lbl_observacion.getAccessibleContext().setAccessibleName("lbl_observacion");
        RegistrarEstudiante.getAccessibleContext().setAccessibleName("btn_RegistrarE");
        ActualizarEstudiante.getAccessibleContext().setAccessibleName("btn_Actualizar");
        BuscarEstudiante.getAccessibleContext().setAccessibleName("btn_Estudiante");
        EliminarEstudiante.getAccessibleContext().setAccessibleName("btn_Eliminar");
        Limpiar.getAccessibleContext().setAccessibleName("btn_Limpiar");
        txt_IDE.getAccessibleContext().setAccessibleName("txt_IDE");
        txt_cedulaE.getAccessibleContext().setAccessibleName("txt_cedulaE");
        txt_nombreE.getAccessibleContext().setAccessibleName("txt_nombreE");
        txt_fechaNac.getAccessibleContext().setAccessibleName("txt_fechaNac");
        txt_direccionE.getAccessibleContext().setAccessibleName("txt_direccionE");
        txt_emailE.getAccessibleContext().setAccessibleName("txt_emailE");
        txt_celularE.getAccessibleContext().setAccessibleName("txt_celularE");
        txt_observacionE.getAccessibleContext().setAccessibleName("txt_observacionE");
        txt_mensajeE.getAccessibleContext().setAccessibleName("txt_mensajeE");
        lbl_Escuela.getAccessibleContext().setAccessibleName("lbl_Escuelas");

        Escuelas.addTab("Estudiante", jPanel2);

        table_general.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_general);
        table_general.getAccessibleContext().setAccessibleName("tbl_general");

        buscarGeneral.setText("Mostrar Estudiantes");
        buscarGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarGeneralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(buscarGeneral)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarGeneral)
                .addContainerGap())
        );

        buscarGeneral.getAccessibleContext().setAccessibleName("btn_buscarTodo");

        Escuelas.addTab("Tabla Estudiantes", jPanel3);

        tabla_escuelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_escuelas);
        tabla_escuelas.getAccessibleContext().setAccessibleName("tbl_escuelas");

        jButton1.setText("Mostrar Escuelas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.getAccessibleContext().setAccessibleName("btn_escuelas");

        Escuelas.addTab("Tabla Escuelas", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escuelas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escuelas)
                .addContainerGap())
        );

        Escuelas.getAccessibleContext().setAccessibleName("tab1_Escuelas");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarGeneralActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Cedula");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha Nacimiento");
        modelo.addColumn("Direccion");
        modelo.addColumn("Email");
        modelo.addColumn("Celular");
        modelo.addColumn("Observaciones");
        table_general.setModel(modelo);
        Object[] arrAlumnos = new Object[8];
        for(AlumnosDS alum: AlumnosBDD.getListAlumnos()){
            arrAlumnos[0] = alum.getId_alu();
            arrAlumnos[1] = alum.getCedula_alu();
            arrAlumnos[2] = alum.getNombre_alu();
            arrAlumnos[3] = alum.getFechaNac_alu();
            arrAlumnos[4] = alum.getDireccion_alu();
            arrAlumnos[5] = alum.getEmail_alu();
            arrAlumnos[6] = alum.getCelular_alu();
            arrAlumnos[7] = alum.getObservaciones_alu();
            modelo.addRow(arrAlumnos);
        }
        table_general.setModel(modelo);
    }//GEN-LAST:event_buscarGeneralActionPerformed

    private void txt_nombreEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreEActionPerformed

    private void txt_cedulaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedulaEActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        txt_IDE.setText("");
        txt_cedulaE.setText("");
        txt_nombreE.setText("");
        txt_fechaNac.setText("");
        txt_direccionE.setText("");
        txt_emailE.setText("");
        txt_celularE.setText("");
        txt_observacionE.setText("");
        cargarEscuelas(0);
    }//GEN-LAST:event_LimpiarActionPerformed

    private void EliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEstudianteActionPerformed
        String resp = AlumnosBDD.eliminarAlumno(txt_IDE.getText());
        txt_IDE.setText("");
        txt_cedulaE.setText("");
        txt_nombreE.setText("");
        txt_fechaNac.setText("");
        txt_direccionE.setText("");
        txt_emailE.setText("");
        txt_celularE.setText("");
        txt_observacionE.setText("");
        txt_mensajeE.setText(resp);
        cargarEscuelas(0);
    }//GEN-LAST:event_EliminarEstudianteActionPerformed

    private void BuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarEstudianteActionPerformed
        AlumnosDS alum = AlumnosBDD.buscarAlumno(txt_IDE.getText());
        txt_IDE.setText(alum.getId_alu()+"");
        txt_cedulaE.setText(alum.getCedula_alu());
        txt_nombreE.setText(alum.getNombre_alu());
        txt_fechaNac.setText(alum.getFechaNac_alu());
        txt_direccionE.setText(alum.getDireccion_alu());
        txt_emailE.setText(alum.getEmail_alu());
        txt_celularE.setText(alum.getEmail_alu());
        txt_observacionE.setText(alum.getEmail_alu());
        cargarEscuelas(alum.getId_escuela());
    }//GEN-LAST:event_BuscarEstudianteActionPerformed

    private void ActualizarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarEstudianteActionPerformed
        EscuelasDS d = (EscuelasDS) list_escuelas.getSelectedItem();
        AlumnosDS alum = new AlumnosDS();
        Integer p_alum = d.getId_escuela();
        alum.setId_alu(Integer.parseInt(txt_IDE.getText()));
        alum.setCedula_alu(txt_cedulaE.getText());
        alum.setNombre_alu(txt_nombreE.getText());
        alum.setFechaNac_alu(txt_fechaNac.getText());
        alum.setDireccion_alu(txt_direccionE.getText());
        alum.setEmail_alu(txt_emailE.getText());
        alum.setCelular_alu(txt_celularE.getText());
        alum.setObservaciones_alu(txt_observacionE.getText());
        alum.setId_escuela(p_alum);
        String resp = AlumnosBDD.actualizarAlumnos(alum);
        txt_IDE.setText("");
        txt_cedulaE.setText("");
        txt_nombreE.setText("");
        txt_fechaNac.setText("");
        txt_direccionE.setText("");
        txt_emailE.setText("");
        txt_celularE.setText("");
        txt_observacionE.setText("");
        txt_mensajeE.setText(resp);
        cargarEscuelas(0);
    }//GEN-LAST:event_ActualizarEstudianteActionPerformed

    private void RegistrarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEstudianteActionPerformed
        EscuelasDS d = (EscuelasDS) list_escuelas.getSelectedItem();
        AlumnosDS alum = new AlumnosDS();
        Integer p_alum = d.getId_escuela();
        alum.setCedula_alu(txt_cedulaE.getText());
        alum.setNombre_alu(txt_nombreE.getText());
        alum.setFechaNac_alu(txt_fechaNac.getText());
        alum.setDireccion_alu(txt_direccionE.getText());
        alum.setEmail_alu(txt_emailE.getText());
        alum.setCelular_alu(txt_celularE.getText());
        alum.setObservaciones_alu(txt_observacionE.getText());
        alum.setId_escuela(p_alum);
        String resp = AlumnosBDD.registrarAlumno(alum);
        txt_IDE.setText("");
        txt_cedulaE.setText("");
        txt_nombreE.setText("");
        txt_fechaNac.setText("");
        txt_direccionE.setText("");
        txt_emailE.setText("");
        txt_celularE.setText("");
        txt_observacionE.setText("");
        txt_mensajeE.setText(resp);
        cargarEscuelas(0);
    }//GEN-LAST:event_RegistrarEstudianteActionPerformed

    private void LimpiarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarTActionPerformed
        txt_mensaje.setText("");
        txt_ID.setText("");
        txt_Nombre.setText("");
        txt_Telefono.setText("");
        txt_Direccion.setText("");
        txt_Email.setText("");
    }//GEN-LAST:event_LimpiarTActionPerformed

    private void EliminarEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEscuelaActionPerformed
        String resp = EscuelasBDD.eliminarEscuelas(txt_ID.getText());
        txt_mensaje.setText(resp);
        txt_ID.setText("");
        txt_Nombre.setText("");
        txt_Telefono.setText("");
        txt_Direccion.setText("");
        txt_Email.setText("");
        cargarEscuelas(0);
    }//GEN-LAST:event_EliminarEscuelaActionPerformed

    private void BuscarEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarEscuelaActionPerformed
        EscuelasDS escu = EscuelasBDD.buscarEscuelas(txt_ID.getText());
        txt_ID.setText(escu.getId_escuela()+"");
        txt_Nombre.setText(escu.getNombre_escuela());
        txt_Telefono.setText(escu.getTelefono_escuela());
        txt_Direccion.setText(escu.getDireccion_escuela());
        txt_Email.setText(escu.getEmail_escuela());
        txt_mensaje.setText(escu.getResultado());
    }//GEN-LAST:event_BuscarEscuelaActionPerformed

    private void ActualizarEscuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarEscuelasActionPerformed
        EscuelasDS escu = new EscuelasDS();
        escu.setId_escuela(Integer.parseInt(txt_ID.getText()));
        escu.setNombre_escuela(txt_Nombre.getText());
        escu.setTelefono_escuela(txt_Telefono.getText());
        escu.setDireccion_escuela(txt_Direccion.getText());
        escu.setEmail_escuela(txt_Email.getText());
        String resp = EscuelasBDD.actualizarEscuelas(escu);
        txt_mensaje.setText(resp);
        txt_ID.setText("");
        txt_Nombre.setText("");
        txt_Telefono.setText("");
        txt_Direccion.setText("");
        txt_Email.setText("");
        cargarEscuelas(0);
    }//GEN-LAST:event_ActualizarEscuelasActionPerformed

    private void RegistrarEscuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEscuelasActionPerformed
        EscuelasDS escu = new EscuelasDS();
        escu.setNombre_escuela(txt_Nombre.getText());
        escu.setTelefono_escuela(txt_Telefono.getText());
        escu.setDireccion_escuela(txt_Direccion.getText());
        escu.setEmail_escuela(txt_Email.getText());
        String resp = EscuelasBDD.registrarEscuelas(escu);
        txt_mensaje.setText(resp);
        txt_Nombre.setText("");
        txt_Telefono.setText("");
        txt_Direccion.setText("");
        txt_Email.setText("");
        cargarEscuelas(0);
    }//GEN-LAST:event_RegistrarEscuelasActionPerformed

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void txt_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TelefonoActionPerformed

    private void txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreActionPerformed

    private void txt_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Direccion");
        modelo.addColumn("Email");
        tabla_escuelas.setModel(modelo);
        Object[] arrEscu = new Object[4];
        for(EscuelasDS escu: EscuelasBDD.getListEscuelas()){
            arrEscu[0] = escu.getId_escuela();
            arrEscu[1] = escu.getNombre_escuela();
            arrEscu[2] = escu.getDireccion_escuela();
            arrEscu[3] = escu.getEmail_escuela();
            modelo.addRow(arrEscu);
        }
        tabla_escuelas.setModel(modelo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void list_escuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_escuelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list_escuelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfasAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfasAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfasAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfasAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfasAplicacion().setVisible(true);
            }
        });
    }

       private void cargarEscuelas(int busca) {
        int index = 1;
        list_escuelas.removeAllItems();
        list_escuelas.addItem("Selecciona una Escuela");
        for(EscuelasDS escu: EscuelasBDD.getListEscuelas()){
            list_escuelas.addItem(escu);
            if(escu.getId_escuela()== busca){
                list_escuelas.setSelectedIndex(index);
            }
            index++;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarEscuelas;
    private javax.swing.JButton ActualizarEstudiante;
    private javax.swing.JButton BuscarEscuela;
    private javax.swing.JButton BuscarEstudiante;
    private javax.swing.JButton EliminarEscuela;
    private javax.swing.JButton EliminarEstudiante;
    private javax.swing.JTabbedPane Escuelas;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton LimpiarT;
    private javax.swing.JButton RegistrarEscuelas;
    private javax.swing.JButton RegistrarEstudiante;
    private javax.swing.JButton buscarGeneral;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Escuela;
    private javax.swing.JLabel lbl_IDe;
    private javax.swing.JLabel lbl_cedulaE;
    private javax.swing.JLabel lbl_celular;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_fechaNac;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_observacion;
    private javax.swing.JComboBox list_escuelas;
    private javax.swing.JTable tabla_escuelas;
    private javax.swing.JTable table_general;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_IDE;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Telefono;
    private javax.swing.JTextField txt_cedulaE;
    private javax.swing.JTextField txt_celularE;
    private javax.swing.JTextField txt_direccionE;
    private javax.swing.JTextField txt_emailE;
    private javax.swing.JTextField txt_fechaNac;
    private javax.swing.JTextField txt_mensaje;
    private javax.swing.JTextField txt_mensajeE;
    private javax.swing.JTextField txt_nombreE;
    private javax.swing.JTextField txt_observacionE;
    // End of variables declaration//GEN-END:variables

}
